# SPDX-FileCopyrightText: Copyright 2026 Rogier van Dalen
#
# SPDX-License-Identifier: Apache-2.0
extends: default
rules:
  document-start:
    present: False
  comments: enable
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: True
