load("@rules_cc//cc:defs.bzl", "cc_library")

# The main target that should be used by other modules that want to depend on
# this library.
# Adoption: if you make sure the name of the target is the same as the name of
# the package, the library can be used with just "//tooling_demo_cpp" instead of
# "//tooling_demo_cpp:tooling_demo_cpp".
cc_library(
    name = "tooling_demo_cpp",
    # Sources to be compiled into the library.
    # Adoption note: for a header-only library, leave this empty.
    srcs = ["source/tooling_demo_cpp/add_two.cpp"],
    # Headers that a user of this library can include.
    hdrs = ["include/tooling_demo_cpp/add_two.hpp"],
    # The prefix to be added to the include path.
    # If the include directory can be set to "include", then include_prefix
    # should be set to "".
    include_prefix = "",
    # The prefix to be stripped from the include path.
    strip_include_prefix = "include/",
    visibility = ["//visibility:public"],
    # Dependencies of this library.
    deps = [
        "@boost.rational",
    ],
)

# All include files, for Doxygen to generate documentation from.
filegroup(
    name = "doc_sources",
    srcs = glob(["include/tooling_demo_cpp/**"]),
    visibility = ["//documentation:__pkg__"],
)
