module(
    name = "tooling_demo_cpp",
    version = "0.2.4",
)

bazel_dep(name = "rules_cc", version = "0.2.22")

# This demo uses Boost.Rational.
bazel_dep(name = "boost.rational", version = "1.90.0.bcr.1")

# Test frameworks that can be used:
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "boost.test", version = "1.90.0.bcr.1")

# IDEs as well as other tools can use a compile_commands.json databse to know
# how files are compiled.
# This is used, for example, for clang-tidy.
# To generate the compile_commands.json file, run
#   bazel run --config=clang @hedron_compile_commands//:refresh_all
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "6eb3ff1de6445355552ef4230be0caf3e1dd27e5",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
)

# Python packages, which are solely for generating documentation with Sphinx.
# See documentation/BUILD.bazel.
bazel_dep(name = "rules_python", version = "2.3.3")
bazel_dep(name = "sphinxdocs", version = "2.3.3")
bazel_dep(name = "platforms", version = "1.1.0")

# Python toolchain
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.12",
)
use_repo(python, "python_3_12", "python_3_12_host")

# uv toolchain, only used for locking requirements
uv = use_extension(
    "@rules_python//python/uv:uv.bzl",
    "uv",
    # Use `dev_dependency` so that the toolchains are not defined pulled when
    # your module is used elsewhere.
    dev_dependency = True,
)
uv.configure(version = "0.6.2")

# pip hub, built from the lock file generated by uv.
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.12",
    requirements_lock = "//documentation:requirements.txt",
)
use_repo(pip, "pypi")

# Doxygen, for generating C++ API documentation.
bazel_dep(name = "rules_doxygen", version = "2.6.4")

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
use_repo(doxygen_extension, "doxygen")
