module(
    name = "tooling_demo",
    version = "0.1.0",
    # use compatibility_level to indicate breaking compatibility
)

bazel_dep(name = "rules_cc", version = "0.2.22")

# This demo uses Boost.Rational.
bazel_dep(name = "boost.rational", version = "1.90.0.bcr.1")

# Test frameworks that can be used:
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "boost.test", version = "1.90.0.bcr.1")

# Run clang-tidy, with `bazel ... --config clang-tidy`.
# clang-tidy requires access to included files, so it is most useful to treat
# it, effectively, as a compiler.

# (2024) The "bazel_clang_tidy" repository does not seem to be very actively
# maintained, but it does do the job.
# Except that there does not seem to be a bzlmod registry that has it.
# So give the Git source explicitly:
bazel_dep(name = "bazel_clang_tidy", version = "")
git_override(
    module_name="bazel_clang_tidy",
    remote="https://github.com/erenon/bazel_clang_tidy.git",
    commit='c4d35e0d0b838309358e57a2efed831780')