module(
    name = "tooling_demo",
    version = "0.1.0",
    # use compatibility_level to indicate breaking compatibility
)

bazel_dep(name = "rules_cc", version = "0.2.22")

# This demo uses Boost.Rational.
bazel_dep(name = "boost.rational", version = "1.90.0.bcr.1")

# Test frameworks that can be used:
bazel_dep(name = "googletest", version = "1.15.2")
bazel_dep(name = "boost.test", version = "1.90.0.bcr.1")

# IDEs as well as other tools can use a compile_commands.json databse to know
# how files are compiled.
# This is used, for example, for clang-tidy.
# To generate the compile_commands.json file, run
#   bazel run --config=clang @hedron_compile_commands//:refresh_all
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
    commit = "6eb3ff1de6445355552ef4230be0caf3e1dd27e5",
)