version = 1

# Code (C++, Python, Bazel, YAML) is licensed under Apache-2.0, and
# documentation (reStructuredText, Markdown) under CC-BY-4.0.
# Both carry SPDX headers in the file itself.

# Configuration files are dedicated to the public domain with CC0-1.0, which
# REUSE recommends for files that are not meaningfully copyrightable.
[[annotations]]
path = [
  ".bazelversion",
  ".bcr/**",
  ".clang-format",
  ".clang-tidy",
  ".gitignore",
  ".vscode/**",
  ".yamllint.yaml",
  "MODULE.bazel.lock",
  "documentation/conf.py",
  "documentation/requirements.in",
  "documentation/requirements.txt",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
