name: Check formatting

on:
  push:
    branches: [ main, develop, test-github-actions ]
  pull_request:
    branches: [ main, develop, test-github-actions ]

  workflow_dispatch:

jobs:
  check-formatting:
    # Use the standard clang-format on the operation system.
    runs-on: ubuntu-26.04
        
    steps:
    - uses: actions/checkout@v7
  
    - name: Setup buildifier
      uses: jbajic/setup-buildifier@v1
      with:
        version: 7.1.1

    - name: Check formatting of Bazel files
      run: buildifier -mode=check -lint=off -r .

    - name: Check formatting of C++ files
      shell: bash
      # This should show incorrectly formatted code, and return with a nonzero
      # exit code if there are formatting problems.
      run: clang-format --dry-run -Werror `find . -name '*.?pp'`
      # It might be useful to hide commits that only format code from git blame:
      # https://docs.github.com/en/repositories/working-with-files/using-files/
      # viewing-a-file#ignore-commits-in-the-blame-view
