name: Pre-commit checks
on:
  push:
    branches: [main, develop, test-github-actions]
  pull_request:
    branches: [main, develop, test-github-actions]
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      # Install a fixed version of clang-format.
      - name: Install clang-format 21
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-21
          echo "CLANG_FORMAT=clang-format-21" >> "$GITHUB_ENV"
      - name: Show clang-format version
        run: clang-format-21 --version
      - uses: pre-commit/action@v3.0.1
